import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Primeiros passos',
      collapsed: false,
      items: [
        'getting-started/installation',
        'getting-started/configuration',
        'getting-started/scripts',
      ],
    },
    {
      type: 'category',
      label: 'Arquitetura',
      items: [
        'architecture/overview',
        'architecture/frontend',
        'architecture/backend',
        'architecture/database',
        'architecture/shared-package',
      ],
    },
    {
      type: 'category',
      label: 'Referência',
      items: ['reference/api', 'reference/domain-model', 'reference/environment'],
    },
    {
      type: 'category',
      label: 'Operações',
      items: [
        'operations/development',
        'operations/testing-quality',
        'operations/deployment',
        'operations/contributing',
      ],
    },
    {
      type: 'category',
      label: 'Plano de implementação',
      link: { type: 'doc', id: 'tasks/README' },
      items: [{ type: 'autogenerated', dirName: 'tasks' }],
    },
  ],
};
export default sidebars;
